version: '3.9'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "3001:3001"
    image: "api_image"
    env_file:
      - .env
  nginx:
    container_name: nginx
    restart: always
    build:
        context: .
        dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    image: "nginx_image"
    env_file:
      - .env
